### ISSUE TITLE
使用github actions进行自动签到有被封的风险

### ISSUE THREAD

**Issue by everything411** [YoungKlaus/BIT_Auto_Leave#2]
see https://bbs.zsxwz.com/thread-4175.htm
可能比较好的方案是部署到国内服务商的函数计算上，有免费额度，仅签到是够用的

**Comment by YoungKlaus** [comment]
谢谢你的建议。我之前挂过一年的腾讯云函数，但是今年已经没有免费额度了。action滥用被封应该是去年的事，我已经好久没听到这方面的消息了，我自己就有一个机场签到的action挂了一年多也没什么事。如果有好用的平台的话会再考虑。
